### ISSUE TITLE
https://pypi.org/project/OpenNMT-py/

### ISSUE THREAD

**Issue by vince62s** [Pangeamt/pangeamt_toolkit#1]
Hello Guys,

I am the maintainer of OpenNMT-py on Github.
We are about to make it pypi compatible but we discovered that you guys registered already the OpenNMT-py project on pypi.org

Can you please delete it so that we can keep this in a legit way ?
Many thanks,
Vincent

**Comment by 333aleix333** [comment]
Hello, I have deleted the project, the name is available again. Sorry for the inconveniences.

**Comment by vince62s** [comment]
Thanks
